version: 0.2


phases:
  install:
    commands:
      - echo Nothing to do in the install phase
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo "ECR get login"  
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)  
      - REPOSITORY_URI=423661677571.dkr.ecr.us-east-1.amazonaws.com/pizza-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo $COMMIT_HASH
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo $CODEBUILD_BUILD_ID
      - echo $IMAGE_TAG  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"pizza-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
