name: burger-App 

on:
  workflow_dispatch:
    inputs:
      git_branch_or_tag:
        description: 'git_branch_or_tag'
        required: true
      docker_tag:
        description: 'docker_tag'
        required: true
        default: 'false'

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git_branch_or_tag }}
  
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting required vars
        run : |
          echo "short_SHA=$(/usr/bin/git log -1 --format='%H' | cut -c 1-7)" >> $GITHUB_ENV   

      - name: Print variables
        run: | 
          echo ${{ env.github_branch }}
          echo ${{ env.short_SHA }}  
      
      - name: Build and push
        if: ${{ github.event.inputs.docker_tag == 'false' }}
        uses: docker/build-push-action@v2
        with:
          context: burger-app/
          push: true
          tags: saiakhil46/burger-app:${{ github.event.inputs.git_branch_or_tag }}-${{ env.short_SHA }}  

      - name: Build and push
        if: ${{ github.event.inputs.docker_tag != 'false' }} 
        uses: docker/build-push-action@v2
        with:
          context: burger-app/
          push: true
          tags: saiakhil46/burger-app:${{ github.event.inputs.docker_tag }}    
