name: Pizza-App 

on:
  workflow_dispatch:
    inputs:
      git_branch_or_tag:
        description: 'git_branch_or_tag'
        required: true
      docker_tag:
        description: 'docker_tag'
        required: false

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.git_branch_or_tag }}
  
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print variables
        run: | 
          echo ${{ github.sha[0:8] }}
          echo ${{ github.ref }}    
      
        if: ${{ ! github.event.inputs.docker_tag }} 
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: pizza-app/
          push: true
          tags: saiakhil46/pizza-app:${{ github.event.inputs.git_branch_or_tag }}-${{ github.sha }}

        if: ${{ github.event.inputs.docker_tag }} 
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: pizza-app/
          push: true
          tags: saiakhil46/pizza-app:${{ github.event.inputs.docker_tag }}    
