name: Pizza-App-CD

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'docker_tag'
        required: true

jobs:
  Deploy-To-EKS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Default)
        uses: actions/checkout@v2
  
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: helm upgrade pizza-app --install --atomic --wait pizza-app/helm-chart/pizza-app -f pizza-app/helm-chart/override.yaml --set image.repository=${{ github.event.inputs.docker_tag }}